### ISSUE TITLE
BDD Test Pinia/class-component impact thoroughly on UI

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#1161]
- [x] I confirm that I'm a developer of FDM Monster and allowed to use this template.

**Description**
Go through all essentials and ensure everything works.
- [x] SideNav opens normally again
- [x] Dialogs open research
- [x] #1162 (similar to floor dialog)
- [x] #1165
- [x] Performance UI lot of printers https://github.com/fdm-monster/fdm-monster/issues/1152
- [x] Menu PrintTile does not close after click #1168 
- [x] https://github.com/fdm-monster/fdm-monster/issues/1163
- [x] Printer test panel works (frontend side)
- [x] https://github.com/fdm-monster/fdm-monster/issues/1164
- [x] Avatar not loading for printer group and floor dialog
- [x] Printer Maint isValid
- [x] Update group not passed to update dialog
- [x] Printer API key is not loaded to form (cannot pass validation)
- [x] CRUD works (floor create)

**Comment by davidzwa** [comment]
![image](https://user-images.githubusercontent.com/6005355/201294000-d0ccc6d3-6686-4160-bd07-781c874716f4.png)
Job not set
