### ISSUE TITLE
Printer tile redesign

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#2146]
Redesign of the printer tile looks.

## Task description
- [x] Implement the "dark mode" "red" version of the design below
- [ ] Color the progress bar according to status of the printer, leave the tile color in one color
  - [ ] Ensure the print completion is mapped to a color: blue, red, green mean printing, error and completed respectively
- [ ] Keep in mind and create follow-up task for adding more information to a printer tile (label, sheet, nozzle, etc) but keep it clean

![image](https://github.com/fdm-monster/fdm-monster/assets/834643/a61b0028-27e2-4c18-9253-b36efd90272f)

![image](https://github.com/fdm-monster/fdm-monster/assets/834643/91074c86-6e09-4d4b-9c3d-047e94903753)
