### ISSUE TITLE
Validate printer URL before saving to database and provide feedback

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#2196]
When creating or updating a printer with an invalid URL, the URL should be validated quickly. This means the URL and apiKey should be valid before submitting the changed value (in printer dialog). If not, show an error clearly.

## Task Description
- [x] Implement URL + apiKey validation for OctoPrint in the backend before creating/updating a printer (dialog)
- [x] If validation fails, present a clear message in the create/update dialog
- [x] If validation succeeds, clearly present this in the dialog with green snackbar
- [x] Add force save checkbox
  
## Original error
TypeError [ERR_INVALID_URL]: Invalid URL
