### ISSUE TITLE
Ensure file upload limit is configurable through env or settings

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#2318]
Files are uploaded to the server through the library `multer`. [This multer service](https://github.com/fdm-monster/fdm-monster/blob/d7c0173d5768c8100f7df25f1a31a89a436dc9fc/src/services/core/multer.service.ts#L94) should be adjusted to allow for a limited file upload size. Right now it seems to be infinite.

## Task description
- [ ] Add an upload limit to ServerSettings settings with default value '200MB'.
- [ ] Adjust the multer service, add a file upload limit that is based on ServerSettings. Allow only specific values: '50MB', '75MB', '100MB', '200MB, '300MB', '400MB' and '500MB'
- [ ] Add UI to select from the above limits

**Comment by davidzwa** [comment]
At this point in time this issue has not been reported by users over the past 3 years. Therefore it seems that it is not needed. Closing as unplanned.
