### ISSUE TITLE
Feat: upload gcode directly from PrusaSlicer and/or Cura

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#2436]
Build a feature to support uploading new GCode files from a slicer like Slic3r, PrusaSlicer, Cura, OrcaSlicer, Superslicer and others.

## Acceptance criteria
- [ ] Build an API endpoint which can accept gcode files
- [ ] Build functionality to store the gcode file
- [ ] Build a UI page which can show these "queued" files as a list
  - [ ] Implement sending the file to a printer by selecting a printer from a select list (simple)
  - [ ] Investigate how drag n drop can be used to improve sending the file to the right printer
- [ ] Create documentation for using the feature with certain slicers (and the supported version of each)
