### ISSUE TITLE
UPDATE `@fdm-monster/client` will be split to a separate repository

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#257]
- [x] I confirm that I'm a developer of FDM Monster and allowed to use this template.

**Description**
The client package `@fdm-monster/client` will move to the repository https://github.com/fdm-monster/fdm-monster-client
This allows us to keep developing the current client version `0.3.3`, whilst working on the new Vue3 version of the client.

Prerequisites:
- [x] Move to Pinia in Vue2 #1101 
- [x] Remove Vuex + Vuex decorators
- [x] Remove class components
- [x] Switch to SocketIO
- [ ] Fix performance issues https://github.com/fdm-monster/fdm-monster/issues/1152

This new version aims to have the following specs:
- [x] ✔️ Composition/Options API
- [x] ✔️Pinia (instead of Vuex)
- [x] ✔️Vite (🚀 amazing experience so far)
- [x] ✔️Less outdated/broken packages like `vue-class-component` or `vue-property-decorator` with no maintenance
- [x] 🐜🐜🐜 Vuetify forms + FormVueLate + vee-validate without massive effort
- [x] 📆 Self-written Bus and SSE implementation (or SocketIO?)
- [x] Await Vuetify 3.0
- [ ] Port over Vue2 code from newest Vue2 work
- [ ] Replace SSE with SocketIO
- [ ] Fix printer tile responsiveness (both v0.1 Vue2 and v1 Vue3 client)
- [ ] Await Vuetify 3.1 (data-table, calendar, etc)
- [ ] 📆Version range 1.0.0-alpha 1.0.0-beta 1.0.0-rc1 and finally 1.0.0
- [ ] 📆Test coverage above 30%
