### ISSUE TITLE
Support Moonraker and Klippy API (basics)

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#2797]
Add support for Moonraker based printers.

## Requirements
- [x] #3353 
- [ ] #3352

## Acceptance Criteria
- [x] Build an API client that can query a Moonraker API for at least uploading file, getting the file list and requesting print status
- [x] Add PrinterType to printer API, service, store and database
- [x] Add UI Printer Type selector https://github.com/fdm-monster/fdm-monster-client/tree/1216-add-moonraker-type-selector
- [x] Convert websocket RPC message types
- [x] Listen to websocket events #3170 
- [x] Implement start/stop/cancel file commands 
- [x] Build a websocket implementation which can track job status
  - [x] Parse message and transform them into a basic shape like OctoPrint, and custom format for customization metadata
  - [x] If necessary, standardize/wrap these state models in such a way that the SockIoAdapter for OctoPrint and the WebsocketAdapter for Moonraker behave very similarly
  - [x] Add a printer type in all Websocket setup calls
  - [x] Add printer type to API logic
- [ ] Extend to be able to see print starts, print error/ends, print status and host state changes (shutdown, reboot)
selector to differentiate OctoPrint and Moonraker server types https://github.com/fdm-monster/fdm-monster/issues/3036
- [ ] Build unhappy flow and be resilient against failures https://moonraker.readthedocs.io/en/latest/web_api/#websocket-setup
- [x] Moonraker files differ from OctoPrint shape, decide what to do with existing database columns (maybe standardize file table, and create OctoPrint and Moonraker subtables)
  - [ ] implement hash checks once https://github.com/Arksine/moonraker/issues/849 is complete
- [ ] Add Moonraker API authentication with API Key
- [x] Add Moonraker Websocket authentication throught [oneshot key](https://moonraker.readthedocs.io/en/latest/web_api/#generate-a-oneshot-token)
- [ ] Add Moonraker management to enable authentication, enable api key and create a user saving the API Key as a result

## Further resources
Add a client for this API:
https://moonraker.readthedocs.io/en/latest/web_api/#http-api-overview
Study this RPC (remote procedure call) javascript implement:
https://github.com/Arksine/moontest/blob/master/src/js/main.js#L28
Try to adjust the printer model in such a way that the intended printer model is known beforehand (Klipper or OctoPrint)
Other examples:
https://github.com/MintyTrebor/moonNode/blob/main/MoonNode.js

**Comment by davidzwa** [comment]
Since this is such a wanted feature: active development has started meaning this feature will get full attention from now on.
