### ISSUE TITLE
Rework the print completion & history API to a simpler unnested data structure

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#2845]
The data structure for print completions are too complex. The original design tracked all state changes from OctoPrint as JSON array in the database. The intent was to track event history and have the ability to analyze which prints are active and which are not. 
Sadly, this feature is currently still dependent on volatile cache as the server has no way to currently relate ongoing prints with stored files. This causes the problem that server restarts will lose track of certain prints (I believe... its been a good while since I last worked on this). The original issue was that files can be renamed in OctoPrint, so the file name were not dependable. This is an assumption, and also an edge case.
Other previous attempts (across multiple projects) included:
- sending the meta object to OctoPrint, which could be used as a source of truth. The one problem was that meta can not be overwritten once set, the actual question is whether the file content can be changed by reupload causing a possible mismatched meta object.
- requesting the file hash, which is also a source of truth

## Acceptance criteria
- [ ] (Investigate) support the history plugin for OctoPrint
- [ ] Build a function which can import/fast-forward history from OctoPrint
- [ ] Track print state by file hash, drop correlationId
- [ ] Migrate/remove the "context" data structure from the print completion database models (both sqlite and mongodb)

Fix: correlationId for completion does not work well (find is now a complete database list due to nested JSON)

**Comment by davidzwa** [comment]
Moving this back to the backlog. There are problems with the current completions approach based on mongodb and a lacking design. The proposed changes here are however outdated and should be re-refined.
