### ISSUE TITLE
Implement a OctoPrint backup management page to create/download/restore/delete an OctoPrint backup

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#3092]
A separate page for managing OctoPrint backups as part of epic #2145. 

## Tasks
- [ ] Add a management page to create/download/delete an OctoPrint backup for a printer
- [ ] Add a form field for uploading a backup to restore a specific OctoPrint
  - [ ] Report success or failure from the upload action

## Special note
The user is responsible for managing the backups. This page will not serve as a backup storage management solution.
