### ISSUE TITLE
Enhance YAML dialog: show YAML import results before pressing import

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#3097]
When importing from YAML, the consequences are not always clear to the user.

## Task description
- [x] After file selection immediately parse the file for validation (backend call)
- [x] Report a list of how many printers are found, how many floors are found and the total printers and floors after import
- [x] Process and show any YAML validation errors
- [ ] Create a follow-up enhancement issue to show the user what the grid and floor list will look like after import so they can review
