### ISSUE TITLE
Fix test memory usage (and speed?)

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#3115]
Often when running tests (even more so with coverage or sqlite) the result can be a fatal Javascript heap out of memory error. This is not a problem per se, given we can increase this heap. But its definitely a nuisance. Furthermore, tests are slow to run. I believe this can be improved.

## Task description
- [ ] Investigate what the difference is between these scenarios
  - [ ] running a test without in-memory database
  - [ ] running a test with and without coverage
  - [ ] running a test without supertest and thus without server host
  - [ ] running an integration with and without awilix (Dependency Injection)
- [ ] Profile the CPU and memory usage of a unit test, service test, db+integration test and db+api test
- [ ] Commit these tests to a separate repository and create a follow-up issue to fire/report this on cron-based schedule

## Special note
There seems to be more memory/CPU usage when either running SQLite mode, or test coverage - my intuition says that coverage is the challenge here.
