### ISSUE TITLE
The reprint dialog shows a random file, definitely not the latest selected file

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#3124]
When selecting multiple printers for executing a batch reprint, a user is receiving a file which seems random. 
I believe there is method to this madness, but it does not matter: the latest file to reprint is the one file which is already selected in OctoPrint.

## Task description
- [x] Fetch the job from OctoPrint, if no job exists then do not return that file
- [x] Refer to https://docs.octoprint.org/en/master/api/job.html
- [x] Present this in the same dialog
