### ISSUE TITLE
Add a SQLite standalone version for MonsterPi

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#3154]
When installing MonsterPi it would be very nice for users to not have to deal with MongoDB anymore. Therefore, roll out a version of sqlite next to the normal MongoDB version so users can start trying this experimental but standalone version of FDM Monster.

## Task description
- [ ] Related task https://github.com/fdm-monster/MonsterPi/issues/54
- [ ] Upload SQLite version to same release as MongoDB
- [ ] Test SQLite image
